### ISSUE TITLE
which version python will work with this?

### ISSUE THREAD

**Issue by Ravid-Levy** [xmpppy/xmppd#1]
which version python will work with this?
and do i need old version of ubuntu?

**Comment by snakeru** [comment]
This was written for python2. I don't know if it was ported since then. You can typically install python2 alongside python3 no problem.

**Comment by Ravid-Levy** [comment]
Which specific python 2 will be ok? 
Dis you run it today?


> This was written for python2. I don't know if it was ported since then. You can typically install python2 alongside python3 no problem.

**Comment by snakeru** [comment]
Python is backwards compartible so 2.7 should be OK. Otherwise you can look at commit dates and then guess what version was in use by then. I haven't run this in a long, long time. I also know that someone picked it up and drove it forward quite a bit, but I unfortunately dodn't have his code anymore.

**Comment by Ravid-Levy** [comment]
> Python is backwards compartible so 2.7 should be OK. Otherwise you can look at commit dates and then guess what version was in use by then. I haven't run this in a long, long time. I also know that someone picked it up and drove it forward quite a bit, but I unfortunately dodn't have his code anymore.

* TLS lite
  <http://trevp.net/tlslite/>

* libevent and pyevent (HIGHLY recommended)
  <http://www.monkey.org/~provos/libevent/> and
  <http://www.monkey.org/~dugsong/pyevent/>

* PsyCo (HIGHLY recommended) <http://psyco.sourceforge.net/>
Can I run this code without all these or i need it?

**Comment by snakeru** [comment]
Try it and see what happens :)
